### ISSUE TITLE
Feature request: Specifying files rather than a directory

### ISSUE THREAD

**Issue by mat013** [jruyi/thrift-gradle-plugin#11]
I would like to suggest a feature that would make it possible to specify specific files rather than a directory. 

I imagine a solution where a new property sourceItems is added.
The sourceItems is of type List<File>

Then the CompileThrift.groovy could be modified in the sourceDir method to check if the path 
is a file or a directory in case it is a directory it can find the necessary .thrift files and add them to the sourceItems, if it is a file then it just add a single file to the sourceItems

I can make the change if it will be accepted
then it will be a matter of compileAll() iterate through all sourceItems

**Comment by pamalyshev** [comment]
I've done something that might be useful in https://github.com/pamalyshev/thrift-gradle-plugin/commit/2618dc749fd6e8cbeddd77e0a44edd68cfa3b699
I'm not familiar with groovy nor gradle plugins, so be warned :)

**Comment by mat013** [comment]
Hi Pamalyshev

It seemed like I was not the only one needing it, since you made it :)
I've already made a similar solution a while ago, but I did not take the time to make a pull request.

So I have done so and made a pull request as well.

The solution is quite similar except that mine support strings and multiple folders 
Let me know if you have any comments.

**Comment by agemocui** [comment]
Thanks for the PR. The changes are included in 0.4.0 which has been published.

**Comment by mat013** [comment]
Thanks a lot :)

br

Meang
