### ISSUE TITLE
Support suppression of generated annotations

### ISSUE THREAD

**Issue by emmenlau** [jruyi/thrift-gradle-plugin#18]
Thrift 0.9.3 adds suppression of generated annotations, to avoid the header:
```
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-06-27")
```
This is helpful for people that track the generated sources (i.e. for regression testing).
To use the suppression, run thrift compiler like this:
```
thrift -gen java:generated_annotations=suppress yourfile.thrift
```

**Comment by agemocui** [comment]
Should have been supported as follows:
```groovy
compileThrift {
	generator 'java', 'generated_annotations=suppress'
}
```

**Comment by emmenlau** [comment]
Works perfectly, thanks!
