### ISSUE TITLE
Running thrift gradle plugin under cygwin

### ISSUE THREAD

**Issue by wwarlock** [jruyi/thrift-gradle-plugin#3]
There is the problem with the paths under `cygwin`.
The plugin tries to use windows standart paths (like "C:\windows\").
But under `cygwin` you must escape the slashes (so the path must looks like "C:\\\\windows\\\\") or convert them by the `cygpath` utility.

**Comment by agemocui** [comment]
Use Gradle Project.exec to execute the thrift command.
Please git clone this repo and run "./gradlew publishToMavenLocal" under the project root.
Then add the code below to the build.gradle of your project to verify the fix. Thanks.
```groovy
buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath 'org.jruyi.gradle:thrift-gradle-plugin:0.2.1-SNAPSHOT'
    }
}

apply plugin: 'org.jruyi.thrift'
```

**Comment by wwarlock** [comment]
In the 0.2.1-SNAPSHOT all works fine, thanks.
And that's strange, but today I cannot reproduce the paths bug in 0.2.0.
