### ISSUE TITLE
`outputDir` now passing to "-o" param

### ISSUE THREAD

**Issue by wwarlock** [jruyi/thrift-gradle-plugin#4]
In the "0.2.1-SNAPSHOT" version, you pass the "outputDir" option to the "-o" thrift param.
But that param doesn't disable the "gen-java" folder generation.
I need that the `outputDir` option will passing to "-out" thrift key, or the new option.

**Comment by agemocui** [comment]
The reason to create gen-* folder by default is that the output folder will be a little mess if multiple generators are specified.

However, added a new property "createGenFolder" for task compileThrift. It's true by default. Set this property to false to not create gen-* folder.

**Comment by wwarlock** [comment]
Thanks for that option, but gradle gave me the error `No such property: createGenFolder for class: org.jruyi.gradle.thrift.plugin.CompileThrift_Decorated` until I've added the `@Input` annotation and removed the `private` keyword.
The same with the other options like `outputDir` option.
I don't think that is the absolutely right solution, but it works for me.

**Comment by agemocui** [comment]
I tested and didnt have the problems you mentioned. Could you clear all the gradle caches and try again (remove the folder ~/.gradle and the .gradle folder under project root)? Thank you.

**Comment by wwarlock** [comment]
I've tried to clean the caches, but stiil having the same.

> * What went wrong:                                                                             
> A problem occurred evaluating root project 'server'.                                           
> > No such property: outputDir for class: org.jruyi.gradle.thrift.plugin.CompileThrift_Decorated
> Possible solutions: outputs

**Comment by agemocui** [comment]
Added a test project, tested via travis and the test passed.
Here's the travis build result https://travis-ci.org/jruyi/thrift-gradle-plugin

BTW, I used gitflow branch model for this project before. But thought not really helpful. So I removed develop branch and made master as the default branch. You can run the test by running "./run-tests.sh" under the project root. Thanks.

**Comment by wwarlock** [comment]
I'm sorry that I didn't understand your model. You're didn't mention this, and I'm always looked to the master branch.

**Comment by agemocui** [comment]
Sorry, my bad. If you are interested, you can take a look at [gitflow](http://nvie.com/posts/a-successful-git-branching-model/). All my new commits was in develop branch.

Anyway, please let me know if everything works for you now and close this issue. Then I will make a release for v0.3.0.

Thank you.
