### ISSUE TITLE
org.jruyi.thrift breaks gradle build when cobertura removed

### ISSUE THREAD

**Issue by mcandre** [jruyi/thrift-gradle-plugin#7]
My Hello Thrift project recently switched from Cobertura to JaCoCo for code coverage, as Cobertura fails to support Java 8. However, it looks like the org.jruyi.thrift plugin breaks when Cobertura is removed:

build.gradle:

https://github.com/mcandre/hello-thrift/blob/master/build.gradle
```
$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/andrew.pennebaker/Desktop/src/hello-thrift/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'hello-thrift'.
> Failed to apply plugin [id 'org.gradle.java']
   > Could not find method makeAsDependency() for arguments [null] on task ':compileThrift'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Am I doing something wrong?

System:

* Gradle 2.7
* Java 1.8
* Thrift 0.9.2
* Mac OS X Yosemite 10.10.5

**Comment by agemocui** [comment]
Hi, the fix is in version 0.3.1. So please use
```groovy
plugins {
 id 'org.jruyi.thrift' version '0.3.1'.
}
```
