### ISSUE TITLE
Location of thrift executable

### ISSUE THREAD

**Issue by tonyghita** [jruyi/thrift-gradle-plugin#8]
When using the default `thriftExecutable` value, I get an error that `thrift` cannot be found. My build file looks like:

```groovy
// build.gradle

plugins {
    id "org.jruyi.thrift" version "0.3.1"
}

compileThrift {
    recurse true

    generator 'html'
    generator 'js'
    generator 'js:node'
    generator 'java', 'private-members', 'hashcode'
    generator 'py'
}
```

I can specify `thriftExecutable '/usr/local/bin/thrift'`, and that works locally. However, I can no longer build in other environments where thrift may not be present at that location.

I don't understand why gradle would complain that `thrift` cannot be found, since it is discoverable from my `PATH`, which is available to gradle (it prints out when I run `./gradlew compileThrift --debug`).

Is there some additional configuration I need to have my thrift executable discoverable? Am I going to have to store the value of `which thrift` to `thriftExecutable`?

**Comment by tonyghita** [comment]
Note: I'm using a gradle wrapper @ version 2.7

**Comment by agemocui** [comment]
Where did you run the build? From a terminal or IDE?

**Comment by tonyghita** [comment]
I've run it from the terminal

**Comment by tonyghita** [comment]
The results from running the task without the full path of the `thriftExecutable` supplied:
```
➜  ./gradlew build
:interface:compileThrift FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':interface:compileThrift'.
> A problem occurred starting process 'command 'thrift''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.607 secs
➜  thrift --version
Thrift version 0.9.2
➜ which thrift
/usr/local/bin/thrift
```

**Comment by agemocui** [comment]
Could you tell me your env like OS and JDK version? Also could you make up an example project that can reproduce this issue? Thanks.

**Comment by tonyghita** [comment]
Java 8:
```
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

OS X 10.11
```
$ sw_vers -productVersion 
10.11
```

I do have a multi-module project, if that matters. I'll make an example project with the same structure.

**Comment by agemocui** [comment]
I created a test project at https://github.com/agemocui/thrift-gradle-plugin-test.
Could you get a copy of that project and then run "./gradlew compileThrift --stacktrace" under that project?

**Comment by tonyghita** [comment]
@agemocui thanks for making that sample project. I cloned it and ran `./gradlew compileThrift` which worked without error. I feel like the issue must be something to do with the way I've set up my mulit-module project.

**Comment by tonyghita** [comment]
I modified the test project to be multi-module like mine, but I'm still unable to reproduce the issue :\

**Comment by tonyghita** [comment]
I'm now unable to reproduce the issue in my own project! It must have been something unrelated? Closing this issue.
