### ISSUE TITLE
Using this plugin in conjunction with build task

### ISSUE THREAD

**Issue by hotmeatballsoup** [jruyi/thrift-gradle-plugin#9]
Hi there, I have some general questions surrounding real world usage of this plugin. I created a [StackOverflow question](http://stackoverflow.com/questions/35232344/gradle-thrift-plugin-by-example) if anyone is interested in helping me out! Thanks and great job!

**Comment by agemocui** [comment]
If your project applies the Java plugin too, the generated java source code should be compiled and jared automatically.
